name: Local Config
version: 1.0.0
schema: v1
models:
  - name: Autodetect
    provider: lmstudio
    model: AUTODETECT
    apiBase: http://localhost:1234/v1
  # - name: Qwen2.5-coder-14b
  #   provider: lmstudio
  #   model: qwen/qwen2.5-coder-14b
  #   apiBase: http://localhost:1234/v1
  # - name: gemma-4-e4b-it
  #   provider: lmstudio
  #   model: gemma-4-e4b-it
  #   apiBase: http://localhost:1234/v1
  # - name: devstral-small-2-2512
  #   provider: lmstudio
  #   model: devstral-small-2-2512
  #   apiBase: http://localhost:1234/v1
